language: python
python:
  - '2.7'
  - '3.6'

before_install:
  - openssl aes-256-cbc -K $encrypted_15a04db7c7ae_key -iv $encrypted_15a04db7c7ae_iv
    -in .pypirc.enc -out ~/.pypirc -d
install:
  - pip install -r requirements-dev.txt
  - pyb install_dependencies

script:
  - pyb publish -v

after_success:
  - codecov
deploy:
  - pyb upload -v
