#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: tabstop=4 shiftwidth=4 expandtab number
"""
A commandline wrapper for the python script

Authors: qianweishuo<qzy922@gmail.com>
Date:    2018/9/4 下午10:44
"""

from qPyUtils.system import portforward

if __name__ == '__main__':
    portforward.main()
